# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import errno
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(323, 361)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        Widget.setFont(font)
        self.label_result = QtWidgets.QLabel(Widget)
        self.label_result.setGeometry(QtCore.QRect(0, 0, 511, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(169,166,170);\n"
"color: rgb(255, 255, 255);")
        self.label_result.setTextFormat(QtCore.Qt.AutoText)
        self.label_result.setObjectName("label_result")
        self.btn_zero = QtWidgets.QPushButton(Widget)
        self.btn_zero.setGeometry(QtCore.QRect(0, 290, 121, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_zero.setFont(font)
        self.btn_zero.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_zero.setObjectName("btn_zero")
        self.btn_equal = QtWidgets.QPushButton(Widget)
        self.btn_equal.setGeometry(QtCore.QRect(120, 290, 121, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("background-color: rgb(255,165,0);\n"
"color: rgb(255, 255, 255);")
        self.btn_equal.setObjectName("btn_equal")
        self.btn_1 = QtWidgets.QPushButton(Widget)
        self.btn_1.setGeometry(QtCore.QRect(0, 210, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_1.setObjectName("btn_1")
        self.btn_4 = QtWidgets.QPushButton(Widget)
        self.btn_4.setGeometry(QtCore.QRect(0, 130, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_4.setObjectName("btn_4")
        self.btn_7 = QtWidgets.QPushButton(Widget)
        self.btn_7.setGeometry(QtCore.QRect(0, 50, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(Widget)
        self.btn_8.setGeometry(QtCore.QRect(80, 50, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_8.setObjectName("btn_8")
        self.btn_5 = QtWidgets.QPushButton(Widget)
        self.btn_5.setGeometry(QtCore.QRect(80, 130, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_5.setObjectName("btn_5")
        self.btn_2 = QtWidgets.QPushButton(Widget)
        self.btn_2.setGeometry(QtCore.QRect(80, 210, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_2.setObjectName("btn_2")
        self.btn_9 = QtWidgets.QPushButton(Widget)
        self.btn_9.setGeometry(QtCore.QRect(160, 50, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_9.setObjectName("btn_9")
        self.btn_6 = QtWidgets.QPushButton(Widget)
        self.btn_6.setGeometry(QtCore.QRect(160, 130, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_6.setObjectName("btn_6")
        self.btn_3 = QtWidgets.QPushButton(Widget)
        self.btn_3.setGeometry(QtCore.QRect(160, 210, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"color: rgb(255, 255, 255);")
        self.btn_3.setObjectName("btn_3")
        self.btn_plus = QtWidgets.QPushButton(Widget)
        self.btn_plus.setGeometry(QtCore.QRect(240, 50, 81, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("background-color: rgb(255,165,0);\n"
"color: rgb(255, 255, 255);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_minus = QtWidgets.QPushButton(Widget)
        self.btn_minus.setGeometry(QtCore.QRect(240, 120, 81, 70))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_minus.setFont(font)
        self.btn_minus.setStyleSheet("background-color: rgb(255,165,0);\n"
"color: rgb(255, 255, 255);")
        self.btn_minus.setObjectName("btn_minus")
        self.btn_mul = QtWidgets.QPushButton(Widget)
        self.btn_mul.setGeometry(QtCore.QRect(240, 190, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_mul.setFont(font)
        self.btn_mul.setStyleSheet("background-color: rgb(255,165,0);\n"
"color: rgb(255, 255, 255);")
        self.btn_mul.setObjectName("btn_mul")
        self.btn_div = QtWidgets.QPushButton(Widget)
        self.btn_div.setGeometry(QtCore.QRect(240, 270, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.btn_div.setFont(font)
        self.btn_div.setStyleSheet("background-color: rgb(255,165,0);\n"
"color: rgb(255, 255, 255);")
        self.btn_div.setObjectName("btn_div")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

        self.is_equal = False

        self.add_functions()

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Calculator for you John"))
        self.label_result.setText(_translate("Widget", "0"))
        self.btn_zero.setText(_translate("Widget", "0"))
        self.btn_equal.setText(_translate("Widget", "="))
        self.btn_1.setText(_translate("Widget", "1"))
        self.btn_4.setText(_translate("Widget", "4"))
        self.btn_7.setText(_translate("Widget", "7"))
        self.btn_8.setText(_translate("Widget", "8"))
        self.btn_5.setText(_translate("Widget", "5"))
        self.btn_2.setText(_translate("Widget", "2"))
        self.btn_9.setText(_translate("Widget", "9"))
        self.btn_6.setText(_translate("Widget", "6"))
        self.btn_3.setText(_translate("Widget", "3"))
        self.btn_plus.setText(_translate("Widget", "+"))
        self.btn_minus.setText(_translate("Widget", "-"))
        self.btn_mul.setText(_translate("Widget", "*"))
        self.btn_div.setText(_translate("Widget", "/"))


    def add_functions(self):
        self.btn_zero.clicked.connect(lambda: self.write_number(self.btn_zero.text()))
        self.btn_1.clicked.connect(lambda: self.write_number(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.write_number(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.write_number(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.write_number(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.write_number(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.write_number(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.write_number(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.write_number(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.write_number(self.btn_9.text()))

        self.btn_plus.clicked.connect(lambda: self.write_number(self.btn_plus.text()))
        self.btn_minus.clicked.connect(lambda: self.write_number(self.btn_minus.text()))
        self.btn_mul.clicked.connect(lambda: self.write_number(self.btn_mul.text()))
        self.btn_div.clicked.connect(lambda: self.write_number(self.btn_div.text()))

        self.btn_equal.clicked.connect(self.results)
    
    def write_number(self,number):
        if self.label_result.text() == "0" or self.is_equal:
                self.label_result.setText(number)
                self.is_equal = False
        else:
                self.label_result.setText(self.label_result.text() + number)



    def results(self):
        if not self.is_equal:
                res = eval(self.label_result.text())
                self.label_result.setText("Result: " + str(res))
                self.is_equal = True
        else:
                error = QMessageBox()
                error.setWindowTitle("Error!")
                error.setText("no no noooo")
                error.setIcon(QMessageBox.Warning)
                error.setStandardButtons(QMessageBox.Reset | QMessageBox.Cancel | QMessageBox.Ok )

                error.setDefaultButton(QMessageBox.Ok)
                error.setInformativeText("don't touch twice equal")
                error.setDetailedText("Zero No Dividied number")

                error.buttonClicked.connect(self.popup_action)

                error.exec_()

    def popup_action(self,btn):
        if btn.text() == "Ok":
                print("Ok")
        elif btn.text() == "Reset":
                self.label_result.setText("")
                self.is_equal = False






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
